### ISSUE TITLE
Incorrect install script used for default_install_url when version is latest

### ISSUE THREAD

**Issue by timothyclarke** [petems/vagrant-puppet-install#55]
Using 

- Virtualbox 5.1.18
- vagrant-puppet-install (4.1.0)
- debian/jessie64 as the box 
on Ubuntu 17.04

My vagrant file has
```
Vagrant.configure("2") do |config|
  hosts.each do |host|
    config.vm.define host[:name] do |c|
          c.puppet_install.puppet_version = :latest
```
No matter what the content of puppet_install, I always get  https://raw.githubusercontent.com/petems/puppet-install-shell/master/install_puppet.sh downloaded and run. 
I expect that https://raw.githubusercontent.com/petems/puppet-install-shell/master/install_puppet_agent.sh should be run.
Note I have a related issue [puppet-install-shell/issues/88](https://github.com/petems/puppet-install-shell/issues/88) open for the install script not dealing with bad versions

**Comment by petems** [comment]
@timothyclarke Can you update to the 5.0.0 release of the plugin and try again? It should work now 😄

**Comment by timothyclarke** [comment]
Updated the plugin, it's still failing but I think we've exposed the root of the issue.
Looking at what's happening with version 5 of this plugin AND what was happening with the earlier version version of the plug I'm forced to conclude that something is setting @machine.config.puppet_install.puppet_version to 5.0.0 early in the plugin

```
if @machine.config.puppet_install.puppet_version == 'latest' || @machine.config.puppet_install.puppet_version.match(/^5\..+/)
```
I would expect the conditional to match either latest or a string starting with a 5.
As something is interpreting what is being supplied  `@machine.config.puppet_install.puppet_version == 'latest'` is not being matched.
That's why the earlier version of the plugin was downloading the install script for version 3 and earlier rather than version 4 or later.

When running with **:latest** I'm getting the following
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sh install.sh -v 5.0.0 2>&1

Stdout from the command:

13:38:25 +0000 INFO: Version parameter defined: 5.0.0
13:38:25 +0000 INFO: Matching Puppet version to puppet-agent package version (See http://docs.puppetlabs.com/puppet/latest/reference/about_agent.html for more details)
13:38:25 +0000 INFO: Downloading Puppet 5.0.0 for debian...
13:38:25 +0000 INFO: Debian platform! Lets get you a DEB...
13:38:25 +0000 INFO: Downloading http://apt.puppetlabs.com/puppet5-release-jessie.deb
13:38:25 +0000 INFO:   to file /tmp/install.sh.9319.random_hexdump/puppet5-release-jessie.deb
13:38:25 +0000 INFO: Trying wget...
13:38:25 +0000 INFO: installing puppetlabs apt repo with dpkg...
Selecting previously unselected package puppet5-release.
(Reading database ... 43185 files and directories currently installed.)
Preparing to unpack .../puppet5-release-jessie.deb ...
Unpacking puppet5-release (5.0.0-1jessie) ...
Setting up puppet5-release (5.0.0-1jessie) ...
Ign http://apt.puppetlabs.com jessie InRelease
Get:1 http://apt.puppetlabs.com jessie Release.gpg [841 B]
Get:2 http://apt.puppetlabs.com jessie Release [88.7 kB]
Get:3 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:4 http://apt.puppetlabs.com jessie/puppet5 amd64 Packages [2,481 B]
Get:5 http://security.debian.org jessie/updates/main Sources [211 kB]
Ign http://deb.debian.org jessie InRelease
Hit http://deb.debian.org jessie Release.gpg
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [417 kB]
Hit http://deb.debian.org jessie Release
Hit http://deb.debian.org jessie/main Sources
Hit http://deb.debian.org jessie/main amd64 Packages
Fetched 783 kB in 2s (273 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '5.0.0' for 'puppet-agent' was not found
13:38:29 +0000 CRIT: Installation failed
13:38:29 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
13:38:29 +0000 CRIT: 
13:38:29 +0000 CRIT: Version: 5.0.0
13:38:29 +0000 CRIT: Platform: debian
13:38:29 +0000 CRIT: Platform Version: 8.8
13:38:29 +0000 CRIT: Machine: x86_64
13:38:29 +0000 CRIT: OS: Linux
13:38:29 +0000 CRIT: 
13:38:29 +0000 CRIT: Please detail your operating system type, version and any other relevant details


Stderr from the command:
```

Per comments on the script side, the "latest" version in the repo at https://apt.puppetlabs.com is **5.0.0-1jessie**

When I supply this as the version
```
puppet_version = '5.0.0-1jessie'
```

I get the following error
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vagrant-puppet-install:
*             '5.0.0-1jessie' is not a valid version of Puppet.

            A list of valid versions can be found at: http://docs.puppetlabs.com/release_notes/
```

I don't think the plugin should be interpreting the string provided as the following does work
```
wget http://apt.puppetlabs.com/puppet5-release-jessie.deb
dpkg -i puppet5-release-jessie.deb
apt-get install -y puppet-agent=5.0.0-1jessie
```

**Comment by timothyclarke** [comment]
Looks good now
